// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZi17S8ZOJ8uchwxcS9_sJGVr-sSA6V8',
    appId: '1:988812199212:web:43486619d93cfc862bd889',
    messagingSenderId: '988812199212',
    projectId: 'cuid-artrite',
    authDomain: 'cuid-artrite.firebaseapp.com',
    databaseURL: 'https://cuid-artrite-default-rtdb.firebaseio.com',
    storageBucket: 'cuid-artrite.firebasestorage.app',
    measurementId: 'G-KC7SLPMV5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssZjfJooxQdkEJjF8kkpYJzdBiBtG61I',
    appId: '1:988812199212:android:c4e2f7fe185280932bd889',
    messagingSenderId: '988812199212',
    projectId: 'cuid-artrite',
    databaseURL: 'https://cuid-artrite-default-rtdb.firebaseio.com',
    storageBucket: 'cuid-artrite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGKXvuarrCy_2BQ179bQNfHQBrDCIW-EI',
    appId: '1:988812199212:ios:ef81a6e14de88a052bd889',
    messagingSenderId: '988812199212',
    projectId: 'cuid-artrite',
    databaseURL: 'https://cuid-artrite-default-rtdb.firebaseio.com',
    storageBucket: 'cuid-artrite.firebasestorage.app',
    iosBundleId: 'com.example.cuidArtrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGKXvuarrCy_2BQ179bQNfHQBrDCIW-EI',
    appId: '1:988812199212:ios:ef81a6e14de88a052bd889',
    messagingSenderId: '988812199212',
    projectId: 'cuid-artrite',
    databaseURL: 'https://cuid-artrite-default-rtdb.firebaseio.com',
    storageBucket: 'cuid-artrite.firebasestorage.app',
    iosBundleId: 'com.example.cuidArtrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZi17S8ZOJ8uchwxcS9_sJGVr-sSA6V8',
    appId: '1:988812199212:web:8583c7e8912e4a9e2bd889',
    messagingSenderId: '988812199212',
    projectId: 'cuid-artrite',
    authDomain: 'cuid-artrite.firebaseapp.com',
    databaseURL: 'https://cuid-artrite-default-rtdb.firebaseio.com',
    storageBucket: 'cuid-artrite.firebasestorage.app',
    measurementId: 'G-8TQSKL3XHC',
  );
}
